%%%%%%%%%%%%%%%%%% WE potential and force functions %%%%%%%%%%%%%%%%%%%%%%%

%This function defines the WE potential energy, V, and force, F

%OUTPUTS:
%V = WE potential, F = WE force
%Fx1 = gradient of V in the x1 direction
%Fx2 = gradient of V in the x2 direction

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%define potential energy, V
V = @(x,y) 3*exp(-x.^2-(y-1/3).^2) ...
        -3*exp(-x.^2-(y-5/3).^2) ...
        -5*exp(-(x-1).^2-y.^2) ...
        -5*exp(-(x+1).^2-y.^2) ...
        +0.2*x.^4 ...
        +0.2*(y-1/3).^4;

%define Fx1, the gradient of V in the x1 direction 
Fx1 = @(xs) 6*xs(1,:).*exp(- (xs(2,:) - 1/3).^2 - xs(1,:).^2) ...
    - 5*exp(- (xs(1,:) + 1).^2 - xs(2,:).^2).*(2*xs(1,:) + 2) ... 
    - 5*exp(- (xs(1,:) - 1).^2 - xs(2,:).^2).*(2*xs(1,:) - 2) ...
    - 6*xs(1,:).*exp(- (xs(2,:) - 5/3).^2 - xs(1,:).^2) ...
    - (4*xs(1,:).^3)/5;

%define Fx2, the gradient of V in the x2 direction
Fx2 = @(xs) 3*exp(- (xs(2,:) - 1/3).^2 - xs(1,:).^2).*(2*xs(2,:) - 2/3) ...
    - 3*exp(- (xs(2,:) - 5/3).^2 - xs(1,:).^2).*(2*xs(2,:) - 10/3) ...
    - (4*(xs(2,:) - 1/3).^3)/5 ...
    - 10*xs(2,:).*exp(- (xs(1,:) - 1).^2 - xs(2,:).^2) ...
    - 10*xs(2,:).*exp(- (xs(1,:) + 1).^2 - xs(2,:).^2);

%define force, F, for underlying overdamped Langevin dynamics
F = @(xs) [Fx1(xs); Fx2(xs)];

